import express from "express";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API routes
  app.post("/api/analyze", async (req, res) => {
    try {
      const { text } = req.body;
      if (!text) {
        return res.status(400).json({ error: "Text is required" });
      }

      const response = await ai.models.generateContent({
        model: "gemini-3.1-pro-preview", // Upgraded model for better reasoning
        contents: `Analyze the following text for an SEO specialist. 
        1. Estimate the likelihood (0-100) that this text was generated by an AI.
        2. Evaluate readability (0-100).
        3. Identify the overall sentiment.
        4. Extract top 5 keywords and their density.
        5. Provide 3-5 actionable SEO suggestions to make it more "human" and search-engine friendly.
        6. Provide a detailed qualitative analysis.

        Text to analyze:
        "${text}"`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              aiLikelihood: { type: Type.NUMBER },
              readabilityScore: { type: Type.NUMBER },
              sentiment: { type: Type.STRING },
              keywordDensity: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    word: { type: Type.STRING },
                    count: { type: Type.NUMBER },
                    percentage: { type: Type.NUMBER }
                  },
                  required: ["word", "count", "percentage"]
                }
              },
              seoSuggestions: {
                type: Type.ARRAY,
                items: { type: Type.STRING }
              },
              detailedAnalysis: { type: Type.STRING }
            },
            required: ["aiLikelihood", "readabilityScore", "sentiment", "keywordDensity", "seoSuggestions", "detailedAnalysis"]
          }
        }
      });

      const result = JSON.parse(response.text || "{}");
      res.json(result);
    } catch (error) {
      console.error("Analysis error:", error);
      res.status(500).json({ error: "Failed to analyze content" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
    app.get("*", (req, res) => {
      res.sendFile("dist/index.html", { root: "." });
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
