import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export interface AnalysisResult {
  aiLikelihood: number; // 0 to 100
  readabilityScore: number; // 0 to 100
  sentiment: string;
  keywordDensity: { word: string; count: number; percentage: number }[];
  seoSuggestions: string[];
  detailedAnalysis: string;
}

export async function analyzeContent(text: string): Promise<AnalysisResult> {
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Analyze the following text for an SEO specialist. 
    1. Estimate the likelihood (0-100) that this text was generated by an AI.
    2. Evaluate readability (0-100).
    3. Identify the overall sentiment.
    4. Extract top 5 keywords and their density.
    5. Provide 3-5 actionable SEO suggestions to make it more "human" and search-engine friendly.
    6. Provide a detailed qualitative analysis.

    Text to analyze:
    "${text}"`,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          aiLikelihood: { type: Type.NUMBER },
          readabilityScore: { type: Type.NUMBER },
          sentiment: { type: Type.STRING },
          keywordDensity: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                word: { type: Type.STRING },
                count: { type: Type.NUMBER },
                percentage: { type: Type.NUMBER }
              },
              required: ["word", "count", "percentage"]
            }
          },
          seoSuggestions: {
            type: Type.ARRAY,
            items: { type: Type.STRING }
          },
          detailedAnalysis: { type: Type.STRING }
        },
        required: ["aiLikelihood", "readabilityScore", "sentiment", "keywordDensity", "seoSuggestions", "detailedAnalysis"]
      }
    }
  });

  try {
    return JSON.parse(response.text || "{}");
  } catch (e) {
    console.error("Failed to parse Gemini response", e);
    throw new Error("Failed to analyze content");
  }
}
